export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const PEOPLE_LOADED = 'PEOPLE_LOADED';
export const PLANETS_LOADED = 'PLANETS_LOADED';
export const FILMS_LOADED = 'FILMS_LOADED';
export const SPECIES_LOADED = 'SPECIES_LOADED';
export const VEHICLES_LOADED = 'VEHICLES_LOADED';
export const STARSHIPS_LOADED = 'STARSHIPS_LOADED';
